### PR TITLE
Add stwcs python 2.7 advisory

### PR DESCRIPTION
**Pull request by jhunkeler**
Need feedback before merging.

cc @mcara

### CODE REVIEW

**Comment by mcara** [comment]
@jhunkeler Thank you!

**Comment by jhunkeler** [comment]
1 of 3 is good enough for me ;)
Merging.

**Comment by pllim** [comment]
@mcara , does this fix your issue with that ServiceNow incident?

**Comment by mcara** [comment]
Well, kind of ... It does not really fix the real bug: it just reverts to the old, working version of `stwcs`. In that sense it does fix the ServiceNow issue.

**Pull request merged**
